### ISSUE TITLE
error after ruuning script

### ISSUE THREAD

**Issue by Shane1033** [SkypLabs/probequest#44] opened 2021-08-09 17:40 UTC
i have a fully updated kali machine and have installed and tried to run the script and i'm getting an error message.
in the example you can see my script version and my adapter is in monitor mode. Any ideas how to fix this? thanks

                                                                                                                                                             
┌──(kali㉿kali)-[~]
└─$ sudo airmon-ng       

PHY     Interface       Driver          Chipset

phy0    wlan0           88XXau          Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac 2T2R DB WLAN Adapter

                                                                                                                                                             
┌──(kali㉿kali)-[~]
└─$ sudo probequest --version
0.7.2
                                                                                                                                                             
┌──(kali㉿kali)-[~]
└─$ sudo probequest --i wlan0
[*] Start sniffing probe requests...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/scapy/pipetool.py", line 114, in run
    p.start()
  File "/usr/lib/python3/dist-packages/scapy/scapypipes.py", line 51, in start
    self.s = conf.L2listen(iface=self.iface, filter=self.filter)
  File "/usr/lib/python3/dist-packages/scapy/arch/linux.py", line 407, in __init__
    attach_filter(self.ins, filter, iface)
  File "/usr/lib/python3/dist-packages/scapy/arch/linux.py", line 142, in attach_filter
    bp = compile_filter(bpf_filter, iface)
  File "/usr/lib/python3/dist-packages/scapy/arch/common.py", line 128, in compile_filter
    raise Scapy_Exception(
scapy.error.Scapy_Exception: Failed to compile filter expression type mgt subtype probe-req (-1)

**Comment by SkypLabs** [comment] 2021-08-09 19:25
Hi @Shane1033,

This is a duplicate of #39.

Please check the existing issues before opening a new one. Thanks.

**Closed** 2021-08-09 19:25 UTC
Labels: duplicate
