### ISSUE TITLE
Failed to compile filter expression type mgt subtype probe-req (-1)

### ISSUE THREAD

**Issue by ludflahs** [SkypLabs/probequest#40] opened 2021-02-13 04:14 UTC
When I run i get this error: 

airmon-ng start wlan0

PHY     Interface       Driver          Chipset

phy0    wlan0           mt7601u         Edimax Technology Co., Ltd Edimax Wi-Fi
                (monitor mode enabled)

                                                                           
┌──(root💀kali)-[/home/kali]
└─# probequest -i wlan0
[*] Start sniffing probe requests...
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/scapy/sendrecv.py", line 906, in _run
    sniff_sockets[L2socket(type=ETH_P_ALL, iface=iface,
  File "/usr/lib/python3/dist-packages/scapy/arch/linux.py", line 407, in __init__
    attach_filter(self.ins, filter, iface)
  File "/usr/lib/python3/dist-packages/scapy/arch/linux.pn: Failed to compile filter expression type mgt subtype probe-req (-1)
^C[*] Stopping the threads...

Probequest 0.7.2 version, monitor mode enabled, and i'm using usb wireless adapter " Edimax Technology Co., Ltd Edimax Wi-Fi" via usb on virtual box kali linux

**Comment by SkypLabs** [comment] 2021-02-13 14:48
Hi @ludflahs,

Thanks for you report.

I think it's a duplicate of https://github.com/SkypLabs/probequest/issues/39. Can you check your version of libpcap?

**Comment by ludflahs** [comment] 2021-02-13 18:29
Oh yeah it's a duplicate, sorry. My version of libpcap :

apt-get install libpcap0.8                                       
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libpcap0.8 is already the newest version (1.10.0-2).
0 upgraded, 0 newly installed, 0 to remove and 25 not upgraded.

I make some search and when i try install previous version says that not found:

apt-get install libpcap0.8=1.9.1                                 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Version '1.9.1' for 'libpcap0.8' was not found

I made some search on repositorys and how to imrpove previous versions but I'm really struggling to do it. Can you help me?

**Comment by SkypLabs** [comment] 2021-02-19 23:05
No worries :)

I saw that you got some help in #39. As a consequence, I close this issue.

**Closed by SkypLabs** 2021-02-19 23:05 UTC
Labels: bug, duplicate
