### ISSUE TITLE
Exception in thread Thread-2:

### ISSUE THREAD

**Issue by Elanius88** [SkypLabs/probequest#42] opened 2021-04-02 12:48 UTC
## Describe the bug

I've installed probequest, but when I try to run it, it returns this error:
`[*] Start sniffing probe requests...
[!] ESSID filters: None
[!] ESSID regex: None
[!] Ignore case: False
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/scapy/sendrecv.py", line 906, in _run
    sniff_sockets[L2socket(type=ETH_P_ALL, iface=iface,
  File "/usr/lib/python3/dist-packages/scapy/arch/linux.py", line 407, in __init__
    attach_filter(self.ins, filter, iface)
  File "/usr/lib/python3/dist-packages/scapy/arch/linux.py", line 142, in attach_filter
    bp = compile_filter(bpf_filter, iface)
  File "/usr/lib/python3/dist-packages/scapy/arch/common.py", line 128, in compile_filter
    raise Scapy_Exception(
scapy.error.Scapy_Exception: Failed to compile filter expression type mgt subtype probe-req (-1)`

## To Reproduce

Install: probequest -i wlan0 --debug  
command used: probequest -i wlan0mon --debug  (at first I tried without debug of course)

## Expected behaviour
Scan wireless networks :)

## Execution environment

Please complete the following information:

 - **OS:** [e.g. Debian Stretch]           **Kali 2021.1**
 - **Python version:** [e.g. 3.6]          **Python 3.9.1+**
 - **ProbeQuest version:** [e.g. 0.7.0]     **0.7.2**
 - **Method of installation:** [e.g. pip]       **pip3 install --upgrade probequest**

**Comment by SkypLabs** [comment] 2021-04-02 18:23
Hi,

Thank you for your report but it seems to be a duplicate of https://github.com/SkypLabs/probequest/issues/39.

You will find a workaround to this issue in the other thread. It is not caused by ProbeQuest itself but by a recent version of libpcap.

**Closed by SkypLabs** 2021-04-02 18:23 UTC
Labels: bug

**Comment by SkypLabs** [comment] 2021-04-02 18:28
Of course, feel free to reopen this issue if libpcap is not the cause of your problem.
